use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

// ── 与 scenario.rs 一致的 struct 定义 ──

#[derive(Debug, Clone, Serialize, Deserialize)]
struct Scenario {
    id: String,
    name: String,
    #[serde(rename = "nameCN")]
    name_cn: String,
    description: String,
    #[serde(rename = "playerTitle")]
    player_title: String,
    titles: Vec<TitleDef>,
    events: Vec<EventDef>,
    achievements: Vec<AchievementDef>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct TitleDef {
    level: u64,
    name: String,
    color: String,
    desc: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct EventDef {
    id: String,
    #[serde(rename = "minLevel")]
    min_level: u64,
    #[serde(rename = "minHours")]
    min_hours: u64,
    weight: u32,
    once: bool,
    text: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct AchievementDef {
    id: String,
    name: String,
    desc: String,
    icon: String,
    condition: AchievementCondition,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", content = "value")]
enum AchievementCondition {
    #[serde(rename = "level")]
    Level(u64),
    #[serde(rename = "runtime")]
    Runtime(u64),
    #[serde(rename = "events")]
    EventsCollected(u64),
    #[serde(rename = "titles")]
    TitleCount(u64),
}

// ── YAML Frontmatter ──

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct ScenarioMeta {
    id: String,
    name: String,
    name_cn: String,
    description: String,
    player_title: String,
    language: String,
}

// ── 入口 ──

fn main() {
    println!("cargo:rerun-if-changed=scenarios/");

    let scenarios_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("scenarios");
    if !scenarios_dir.exists() {
        fs::create_dir_all(&scenarios_dir).expect("Failed to create scenarios dir");
    }

    let mut md_files: Vec<_> = fs::read_dir(&scenarios_dir)
        .expect("Failed to read scenarios dir")
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map_or(false, |ext| ext == "md"))
        .collect();
    md_files.sort_by_key(|e| e.file_name());

    let mut scenarios: Vec<Scenario> = Vec::new();

    for entry in &md_files {
        let path = entry.path();
        let content = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("Failed to read {}: {}", path.display(), e));
        match parse_scenario_md(&content) {
            Ok(scenario) => {
                validate_scenario(&scenario, &path);
                scenarios.push(scenario);
            }
            Err(e) => panic!("Parse error in {}: {}", path.display(), e),
        }
    }

    if scenarios.is_empty() {
        panic!("No .md scenario files found in scenarios/ directory");
    }

    // 生成 scenarios_data.rs → OUT_DIR
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("scenarios_data.rs");

    let mut output = String::from("// Auto-generated by build.rs — do not edit manually\n// Run `cargo build` to regenerate\n\n");

    for (i, scenario) in scenarios.iter().enumerate() {
        let bytes = bincode::serialize(scenario)
            .unwrap_or_else(|e| panic!("Failed to serialize scenario {}: {}", scenario.id, e));
        let ident = format!("SCENARIO_{}", i);
        output.push_str(&format!("pub const {}: &[u8] = &{:?};\n", ident, bytes));
    }

    output.push_str("pub const ALL_SCENARIO_DATA: &[&[u8]] = &[\n");
    for i in 0..scenarios.len() {
        output.push_str(&format!("    SCENARIO_{},\n", i));
    }
    output.push_str("];\n");

    fs::write(&dest_path, output).expect("Failed to write scenarios_data.rs");
    eprintln!(
        "build.rs: parsed {} scenario(s), wrote {}",
        scenarios.len(),
        dest_path.display()
    );
}

// ── .md 解析器 ──

fn parse_scenario_md(content: &str) -> Result<Scenario, String> {
    // 分离 YAML frontmatter 和正文
    let lines: Vec<&str> = content.lines().collect();
    let (meta_yaml, body_start) = extract_frontmatter(&lines)?;

    // 解析 frontmatter
    let meta: ScenarioMeta =
        serde_yaml::from_str(&meta_yaml).map_err(|e| format!("YAML frontmatter error: {}", e))?;

    // 解析各表格区域
    let body_lines = &lines[body_start..];
    let titles = parse_titles(body_lines)?;
    let events = parse_events(body_lines)?;
    let achievements = parse_achievements(body_lines)?;

    if titles.is_empty() {
        return Err("Titles section is empty (need at least 5)".to_string());
    }
    if events.is_empty() {
        return Err("Events section is empty".to_string());
    }

    Ok(Scenario {
        id: meta.id,
        name: meta.name,
        name_cn: meta.name_cn,
        description: meta.description,
        player_title: meta.player_title,
        titles,
        events,
        achievements,
    })
}

/// 从行数组中提取 frontmatter
/// 返回 (yaml文本, 正文起始行索引)
fn extract_frontmatter(lines: &[&str]) -> Result<(String, usize), String> {
    // 第一行必须是 ---
    if lines.is_empty() || lines[0].trim() != "---" {
        return Err("Missing frontmatter delimiter (first line must be '---')".to_string());
    }

    // 找到第二个 ---
    let mut end = None;
    for (i, line) in lines.iter().enumerate().skip(1) {
        if line.trim() == "---" {
            end = Some(i);
            break;
        }
    }

    let end = end.ok_or("Missing closing '---' for frontmatter".to_string())?;

    // YAML 正文 = lines[1..end]
    let yaml_start = lines[1..end]
        .iter()
        .position(|l| !l.trim().is_empty())
        .unwrap_or(0);
    let yaml_end = lines[1..end]
        .iter()
        .rposition(|l| !l.trim().is_empty())
        .map(|i| i + 1)
        .unwrap_or(0);
    let yaml_lines = &lines[1 + yaml_start..1 + yaml_end];
    let yaml_text = yaml_lines.join("\n");

    Ok((yaml_text, end + 1))
}

/// 从行数组中定位 ## 标题区域
fn find_section<'a>(lines: &[&'a str], section_name: &str) -> Option<usize> {
    let target = format!("## {}", section_name);
    lines.iter().position(|l| l.trim() == target.as_str())
}

/// 从某个起始位置查找下一个 ## 标题（或文件末尾）
fn next_section_or_end(lines: &[&str], start: usize) -> usize {
    for i in (start + 1)..lines.len() {
        if lines[i].trim().starts_with("## ") {
            return i;
        }
    }
    lines.len()
}

/// 解析 pipe 表格，返回行列表（每行为单元格 Vec）
fn parse_table(lines: &[&str], start: usize, end: usize) -> Vec<Vec<String>> {
    let mut rows: Vec<Vec<String>> = Vec::new();
    let mut in_table = false;

    for i in start..end {
        let line = lines[i].trim();
        if !line.starts_with('|') || !line.ends_with('|') {
            if in_table {
                break; // 表格结束
            }
            continue;
        }
        in_table = true;

        // 跳过分隔符行（|---|---|）
        if line.contains("---") {
            continue;
        }

        // 解析行
        let cells: Vec<String> = line
            .trim_start_matches('|')
            .trim_end_matches('|')
            .split('|')
            .map(|c| c.trim().to_string())
            .collect();

        if !cells.is_empty() {
            rows.push(cells);
        }
    }

    rows
}

/// 规范化列名（用于匹配不同语言的表头）
fn normalize_col(name: &str) -> &str {
    match name {
        "Level" | "等级" | "level" => "level",
        "Name" | "名称" | "名字" | "name" => "name",
        "Color" | "颜色" | "color" => "color",
        "Description" | "描述" | "desc" | "description" => "desc",
        "ID" | "id" | "Id" => "id",
        "MinLevel" | "最低等级" | "min_level" | "minlevel" | "minLevel" => "minlevel",
        "MinHours" | "最低挂机小时数" | "min_hours" | "minhours" | "minHours" => "minhours",
        "Weight" | "权重" | "weight" => "weight",
        "Once" | "只触发一次" | "once" => "once",
        "Text" | "事件文本" | "text" => "text",
        "Icon" | "图标" | "icon" => "icon",
        "ConditionType" | "条件类型" | "condition_type" | "conditiontype" | "conditionType" => "conditiontype",
        "ConditionValue" | "条件值" | "condition_value" | "conditionvalue" | "conditionValue" => "conditionvalue",
        _ => name,
    }
}

// ── Titles 解析 ──

fn parse_titles(body_lines: &[&str]) -> Result<Vec<TitleDef>, String> {
    let section_start = find_section(body_lines, "Titles")
        .ok_or("Missing '## Titles' section")?;
    let section_end = next_section_or_end(body_lines, section_start);

    let rows = parse_table(body_lines, section_start, section_end);
    if rows.len() < 2 {
        return Err("Titles table needs at least header + one row".to_string());
    }

    // 解析表头
    let headers: Vec<String> = rows[0].iter().map(|h| normalize_col(h).to_lowercase()).collect();
    let level_idx = headers.iter().position(|h| h == "level").ok_or("Titles table missing 'Level' column")?;
    let name_idx = headers.iter().position(|h| h == "name").ok_or("Titles table missing 'Name' column")?;
    let color_idx = headers.iter().position(|h| h == "color").ok_or("Titles table missing 'Color' column")?;
    let desc_idx = headers.iter().position(|h| h == "desc").ok_or("Titles table missing 'Description' column")?;

    let mut titles = Vec::new();
    for row in &rows[1..] {
        if row.len() <= *[level_idx, name_idx, color_idx, desc_idx].iter().max().unwrap() {
            continue; // 跳过不完整的行
        }
        titles.push(TitleDef {
            level: row[level_idx].parse::<u64>().map_err(|e| format!("Title level parse error: {}", e))?,
            name: row[name_idx].clone(),
            color: row[color_idx].clone(),
            desc: row[desc_idx].clone(),
        });
    }

    // 校验升序
    for i in 1..titles.len() {
        if titles[i].level <= titles[i - 1].level {
            return Err(format!(
                "Titles not in ascending order: Lv.{} after Lv.{}",
                titles[i].level, titles[i - 1].level
            ));
        }
    }

    if titles.len() < 5 {
        return Err(format!(
            "Need at least 5 titles, got {}",
            titles.len()
        ));
    }

    Ok(titles)
}

// ── Events 解析 ──

fn parse_events(body_lines: &[&str]) -> Result<Vec<EventDef>, String> {
    let section_start = find_section(body_lines, "Events")
        .ok_or("Missing '## Events' section")?;
    let section_end = next_section_or_end(body_lines, section_start);

    let rows = parse_table(body_lines, section_start, section_end);
    if rows.len() < 2 {
        return Ok(Vec::new()); // 允许 0 事件（后面会有校验）
    }

    let headers: Vec<String> = rows[0].iter().map(|h| normalize_col(h).to_lowercase()).collect();
    let id_idx = headers.iter().position(|h| h == "id").ok_or("Events table missing 'ID' column")?;
    let text_idx = headers.iter().position(|h| h == "text").ok_or("Events table missing 'Text' column")?;

    // 可选列
    let minlevel_idx = headers.iter().position(|h| h == "minlevel");
    const MINLEVEL_DEFAULT: u64 = 1;
    let minhours_idx = headers.iter().position(|h| h == "minhours");
    const MINHOURS_DEFAULT: u64 = 0;
    let weight_idx = headers.iter().position(|h| h == "weight");
    const WEIGHT_DEFAULT: u32 = 5;
    let once_idx = headers.iter().position(|h| h == "once");
    const ONCE_DEFAULT: bool = false;

    let mut events = Vec::new();
    let mut ids = std::collections::HashSet::new();

    for row in &rows[1..] {
        if row.len() <= id_idx || row.len() <= text_idx {
            continue;
        }
        let id = row[id_idx].clone();
        if !ids.insert(id.clone()) {
            return Err(format!("Duplicate event ID: {}", id));
        }

        events.push(EventDef {
            id,
            min_level: minlevel_idx.map(|i| row[i].parse::<u64>().unwrap_or(MINLEVEL_DEFAULT)).unwrap_or(MINLEVEL_DEFAULT),
            min_hours: minhours_idx.map(|i| row[i].parse::<u64>().unwrap_or(MINHOURS_DEFAULT)).unwrap_or(MINHOURS_DEFAULT),
            weight: weight_idx.map(|i| row[i].parse::<u32>().unwrap_or(WEIGHT_DEFAULT)).unwrap_or(WEIGHT_DEFAULT),
            once: once_idx.map(|i| parse_bool(&row[i])).unwrap_or(ONCE_DEFAULT),
            text: row[text_idx].clone(),
        });
    }

    Ok(events)
}

fn parse_bool(s: &str) -> bool {
    match s.trim().to_lowercase().as_str() {
        "是" | "yes" | "true" | "1" | "y" => true,
        _ => false,
    }
}

// ── Achievements 解析 ──

fn parse_achievements(body_lines: &[&str]) -> Result<Vec<AchievementDef>, String> {
    let section_start = find_section(body_lines, "Achievements");
    let section_end = match section_start {
        Some(s) => next_section_or_end(body_lines, s),
        None => return Ok(Vec::new()), // 成就可选
    };

    let rows = parse_table(body_lines, section_start.unwrap(), section_end);
    if rows.len() < 2 {
        return Ok(Vec::new());
    }

    let headers: Vec<String> = rows[0].iter().map(|h| normalize_col(h).to_lowercase()).collect();
    let id_idx = headers.iter().position(|h| h == "id").ok_or("Achievements table missing 'ID' column")?;
    let name_idx = headers.iter().position(|h| h == "name").ok_or("Achievements table missing 'Name' column")?;
    let desc_idx = headers.iter().position(|h| h == "desc").ok_or("Achievements table missing 'Description' column")?;
    let condtype_idx = headers.iter().position(|h| h == "conditiontype").ok_or("Achievements table missing 'ConditionType' column")?;
    let condval_idx = headers.iter().position(|h| h == "conditionvalue").ok_or("Achievements table missing 'ConditionValue' column")?;

    let icon_idx = headers.iter().position(|h| h == "icon");

    let mut achievements = Vec::new();
    let mut ids = std::collections::HashSet::new();

    for row in &rows[1..] {
        let max_idx = *[id_idx, name_idx, desc_idx, condtype_idx, condval_idx].iter().max().unwrap();
        if row.len() <= max_idx {
            continue;
        }

        let id = row[id_idx].clone();
        if !ids.insert(id.clone()) {
            return Err(format!("Duplicate achievement ID: {}", id));
        }

        let cond_type = row[condtype_idx].trim().to_lowercase();
        let cond_val = row[condval_idx].parse::<u64>()
            .map_err(|e| format!("Achievement '{}' condition value parse error: {}", id, e))?;

        let condition = match cond_type.as_str() {
            "level" => AchievementCondition::Level(cond_val),
            "runtime" => AchievementCondition::Runtime(cond_val),
            "events" | "eventscollected" => AchievementCondition::EventsCollected(cond_val),
            "titles" | "titlecount" => AchievementCondition::TitleCount(cond_val),
            _ => return Err(format!("Unknown achievement condition type '{}' in '{}'", cond_type, id)),
        };

        achievements.push(AchievementDef {
            id,
            name: row[name_idx].clone(),
            desc: row[desc_idx].clone(),
            icon: icon_idx.map(|i| row[i].clone()).unwrap_or_else(|| "★".to_string()),
            condition,
        });
    }

    Ok(achievements)
}

// ── 内容校验 ──

fn validate_scenario(scenario: &Scenario, path: &Path) {
    // ID 格式：只含小写字母/数字/下划线
    if !scenario
        .id
        .chars()
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
    {
        panic!(
            "Scenario ID '{}' in {} must contain only lowercase letters, digits, and underscores",
            scenario.id,
            path.display()
        );
    }

    // 校验事件
    for event in &scenario.events {
        if event.text.len() < 10 {
            panic!(
                "Event '{}' in {} text too short ({} chars, min 10)",
                event.id,
                path.display(),
                event.text.len()
            );
        }
        if event.weight < 1 || event.weight > 10 {
            panic!(
                "Event '{}' in {} weight {} out of range [1,10]",
                event.id, path.display(), event.weight
            );
        }
    }

    // 校验成就
    for ach in &scenario.achievements {
        match &ach.condition {
            AchievementCondition::Level(v) => {
                if *v > 1000 {
                    panic!("Achievement '{}' level condition {} too high", ach.id, v);
                }
            }
            AchievementCondition::Runtime(v) => {
                if *v > 31_536_000_000 {
                    // 1000 years
                    panic!("Achievement '{}' runtime condition {} too high", ach.id, v);
                }
            }
            _ => {}
        }
    }
}
